// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package domain

import (
	"context"
)

const getLeaders = `-- name: GetLeaders :one
SELECT id, civ_name, leader_name, discord_emoji_string, banned, ranking FROM leaders
`

func (q *Queries) GetLeaders(ctx context.Context) (Leader, error) {
	row := q.db.QueryRowContext(ctx, getLeaders)
	var i Leader
	err := row.Scan(
		&i.ID,
		&i.CivName,
		&i.LeaderName,
		&i.DiscordEmojiString,
		&i.Banned,
		&i.Ranking,
	)
	return i, err
}
