services:
  ci6ndex:
    restart: unless-stopped
    image: ghcr.io/hazzardr/ci6ndex:0.1.0-prerelease1
    depends_on: []
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 200M
        reservations:
          cpus: "0.25"
          memory: 100M
networks: {}