GET http://localhost:8080/health
Accept: application/json

###

GET http://localhost:8080/rankings


###
POST http://localhost:8080/rankings

###

PUT http://localhost:8080/users
Content-Type: application/json

{
  "Name": "Greg",
  "DiscordName": "meowmix"
}

###

GET http://localhost:8080/draft_strategies
###

GET http://localhost:8080/draft_strategies/test