GET http://localhost:8080/health
Accept: application/json

###
POST http://localhost:8080/rankings

###

PUT http://localhost:8080/users
Content-Type: application/json

{
  "Name": "Greg",
  "DiscordName": "meowmix"
}

###

GET http://localhost:8080/draft_strategies
###

GET http://localhost:8080/draft_strategies/test

###

PUT http://localhost:8080/drafts
Content-Type: application/json

{
  "draft_strategy": "AllPick"
}

###
PUT http://localhost:8080/drafts/5/picks
Content-Type: application/json

{
  "leader": {
    "name": "Lautaro",
    "civ": "Mapuche"
  },
  "discord_user": "hazzard_"
}