-- +goose Up
ALTER TABLE leaders ADD COLUMN friendly_name TEXT;

UPDATE leaders SET friendly_name = 'Abraham Lincoln' WHERE id = 1;
UPDATE leaders SET friendly_name = 'Teddy Roosevelt (Bull Moose)' WHERE id = 2;
UPDATE leaders SET friendly_name = 'Teddy Roosevelt (Rough Rider)' WHERE id = 3;
UPDATE leaders SET friendly_name = 'Saladin (Sultan)' WHERE id = 4;
UPDATE leaders SET friendly_name = 'Saladin (Vizier)' WHERE id = 5;
UPDATE leaders SET friendly_name = 'John Curtin' WHERE id = 6;
UPDATE leaders SET friendly_name = 'Montezuma' WHERE id = 7;
UPDATE leaders SET friendly_name = 'Hammurabi' WHERE id = 8;
UPDATE leaders SET friendly_name = 'Pedro II' WHERE id = 9;
UPDATE leaders SET friendly_name = 'Basil II' WHERE id = 10;
UPDATE leaders SET friendly_name = 'Theodora' WHERE id = 11;
UPDATE leaders SET friendly_name = 'Wilfrid Laurier' WHERE id = 12;
UPDATE leaders SET friendly_name = 'Kublai Khan (China)' WHERE id = 13;
UPDATE leaders SET friendly_name = 'Qin Shi Huang (Unifier)' WHERE id = 14;
UPDATE leaders SET friendly_name = 'Qin Shi Huang' WHERE id = 15;
UPDATE leaders SET friendly_name = 'Wu Zetian' WHERE id = 16;
UPDATE leaders SET friendly_name = 'Yongle' WHERE id = 17;
UPDATE leaders SET friendly_name = 'Poundmaker' WHERE id = 18;
UPDATE leaders SET friendly_name = 'Wilhelmina' WHERE id = 19;
UPDATE leaders SET friendly_name = 'Cleopatra (Egyptian)' WHERE id = 20;
UPDATE leaders SET friendly_name = 'Cleopatra (Ptolemaic)' WHERE id = 21;
UPDATE leaders SET friendly_name = 'Ramses II' WHERE id = 22;
UPDATE leaders SET friendly_name = 'Eleanor of Aquitaine (England)' WHERE id = 23;
UPDATE leaders SET friendly_name = 'Elizabeth I' WHERE id = 24;
UPDATE leaders SET friendly_name = 'Victoria (Age of Steam)' WHERE id = 25;
UPDATE leaders SET friendly_name = 'Victoria' WHERE id = 26;
UPDATE leaders SET friendly_name = 'Menelik II' WHERE id = 27;
UPDATE leaders SET friendly_name = 'Catherine (Black Queen)' WHERE id = 28;
UPDATE leaders SET friendly_name = 'Eleanor of Aquitaine (France)' WHERE id = 29;
UPDATE leaders SET friendly_name = 'Catherine (Magnificence)' WHERE id = 30;
UPDATE leaders SET friendly_name = 'Ambiorix' WHERE id = 31;
UPDATE leaders SET friendly_name = 'Tamar' WHERE id = 32;
UPDATE leaders SET friendly_name = 'Frederick Barbarossa' WHERE id = 33;
UPDATE leaders SET friendly_name = 'Ludwig II' WHERE id = 34;
UPDATE leaders SET friendly_name = 'Simón Bolívar' WHERE id = 35;
UPDATE leaders SET friendly_name = 'Gorgo' WHERE id = 36;
UPDATE leaders SET friendly_name = 'Pericles' WHERE id = 37;
UPDATE leaders SET friendly_name = 'Matthias Corvinus' WHERE id = 38;
UPDATE leaders SET friendly_name = 'Pachacuti' WHERE id = 39;
UPDATE leaders SET friendly_name = 'Chandragupta' WHERE id = 40;
UPDATE leaders SET friendly_name = 'Gandhi' WHERE id = 41;
UPDATE leaders SET friendly_name = 'Gitarja' WHERE id = 42;
UPDATE leaders SET friendly_name = 'Hojo Tokimune' WHERE id = 43;
UPDATE leaders SET friendly_name = 'Tokugawa' WHERE id = 44;
UPDATE leaders SET friendly_name = 'Jayavarman VII' WHERE id = 45;
UPDATE leaders SET friendly_name = 'Mvemba a Nzinga' WHERE id = 46;
UPDATE leaders SET friendly_name = 'Nzinga Mbande' WHERE id = 47;
UPDATE leaders SET friendly_name = 'Sejong' WHERE id = 48;
UPDATE leaders SET friendly_name = 'Seondeok' WHERE id = 49;
UPDATE leaders SET friendly_name = 'Alexander' WHERE id = 50;
UPDATE leaders SET friendly_name = 'Mansa Musa' WHERE id = 51;
UPDATE leaders SET friendly_name = 'Sundiata Keita' WHERE id = 52;
UPDATE leaders SET friendly_name = 'Kupe' WHERE id = 53;
UPDATE leaders SET friendly_name = 'Lautaro' WHERE id = 54;
UPDATE leaders SET friendly_name = 'Lady Six Sky' WHERE id = 55;
UPDATE leaders SET friendly_name = 'Genghis Khan' WHERE id = 56;
UPDATE leaders SET friendly_name = 'Kublai Khan (Mongolia)' WHERE id = 57;
UPDATE leaders SET friendly_name = 'Harald Hardrada' WHERE id = 58;
UPDATE leaders SET friendly_name = 'Harald Hardrada (Varangian)' WHERE id = 59;
UPDATE leaders SET friendly_name = 'Amanitore' WHERE id = 60;
UPDATE leaders SET friendly_name = 'Suleiman (Muhteşem)' WHERE id = 61;
UPDATE leaders SET friendly_name = 'Suleiman' WHERE id = 62;
UPDATE leaders SET friendly_name = 'Cyrus' WHERE id = 63;
UPDATE leaders SET friendly_name = 'Nader Shah' WHERE id = 64;
UPDATE leaders SET friendly_name = 'Dido' WHERE id = 65;
UPDATE leaders SET friendly_name = 'Jadwiga' WHERE id = 66;
UPDATE leaders SET friendly_name = 'João III' WHERE id = 67;
UPDATE leaders SET friendly_name = 'Julius Caesar' WHERE id = 68;
UPDATE leaders SET friendly_name = 'Trajan' WHERE id = 69;
UPDATE leaders SET friendly_name = 'Peter' WHERE id = 70;
UPDATE leaders SET friendly_name = 'Robert the Bruce' WHERE id = 71;
UPDATE leaders SET friendly_name = 'Tomyris' WHERE id = 72;
UPDATE leaders SET friendly_name = 'Philip II' WHERE id = 73;
UPDATE leaders SET friendly_name = 'Gilgamesh' WHERE id = 74;
UPDATE leaders SET friendly_name = 'Kristina' WHERE id = 75;
UPDATE leaders SET friendly_name = 'Bà Triệu' WHERE id = 76;
UPDATE leaders SET friendly_name = 'Shaka' WHERE id = 77;
UPDATE leaders SET friendly_name = 'Vercingetorix' WHERE id = 78;
UPDATE leaders SET friendly_name = 'Olympias' WHERE id = 79;
UPDATE leaders SET friendly_name = 'Te'' K''inich II' WHERE id = 80;
UPDATE leaders SET friendly_name = 'Ahiram' WHERE id = 81;
UPDATE leaders SET friendly_name = 'Al-Hasan ibn Sulaiman' WHERE id = 82;
UPDATE leaders SET friendly_name = 'Spearthrower Owl' WHERE id = 83;
UPDATE leaders SET friendly_name = 'Kiviuq' WHERE id = 84;
UPDATE leaders SET friendly_name = 'Trisong Detsen' WHERE id = 85;

-- +goose Down
ALTER TABLE leaders DROP COLUMN friendly_name;
