// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package domain

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlayersToActiveDraft = `-- name: AddPlayersToActiveDraft :one
UPDATE ci6ndex.drafts
SET players = $1
where active=true
RETURNING id, draft_strategy, active, players
`

func (q *Queries) AddPlayersToActiveDraft(ctx context.Context, players []string) (Ci6ndexDraft, error) {
	row := q.db.QueryRow(ctx, addPlayersToActiveDraft, players)
	var i Ci6ndexDraft
	err := row.Scan(
		&i.ID,
		&i.DraftStrategy,
		&i.Active,
		&i.Players,
	)
	return i, err
}

const cancelActiveDrafts = `-- name: CancelActiveDrafts :many
UPDATE ci6ndex.drafts
SET active = false
WHERE active = true
RETURNING id, draft_strategy, active, players
`

func (q *Queries) CancelActiveDrafts(ctx context.Context) ([]Ci6ndexDraft, error) {
	rows, err := q.db.Query(ctx, cancelActiveDrafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ci6ndexDraft
	for rows.Next() {
		var i Ci6ndexDraft
		if err := rows.Scan(
			&i.ID,
			&i.DraftStrategy,
			&i.Active,
			&i.Players,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearOffered = `-- name: ClearOffered :exec
TRUNCATE TABLE ci6ndex.offered
`

func (q *Queries) ClearOffered(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearOffered)
	return err
}

const createActiveDraft = `-- name: CreateActiveDraft :one
INSERT INTO ci6ndex.drafts
(
    draft_strategy, active
) VALUES (
    $1, true
)
RETURNING id, draft_strategy, active, players
`

func (q *Queries) CreateActiveDraft(ctx context.Context, draftStrategy string) (Ci6ndexDraft, error) {
	row := q.db.QueryRow(ctx, createActiveDraft, draftStrategy)
	var i Ci6ndexDraft
	err := row.Scan(
		&i.ID,
		&i.DraftStrategy,
		&i.Active,
		&i.Players,
	)
	return i, err
}

const createDraft = `-- name: CreateDraft :one
INSERT INTO ci6ndex.drafts
(
    draft_strategy
) VALUES (
    $1
)
RETURNING id, draft_strategy, active, players
`

func (q *Queries) CreateDraft(ctx context.Context, draftStrategy string) (Ci6ndexDraft, error) {
	row := q.db.QueryRow(ctx, createDraft, draftStrategy)
	var i Ci6ndexDraft
	err := row.Scan(
		&i.ID,
		&i.DraftStrategy,
		&i.Active,
		&i.Players,
	)
	return i, err
}

const createDraftStrategy = `-- name: CreateDraftStrategy :one
INSERT INTO ci6ndex.draft_strategies
(
    name, description, pool_size, randomize
) VALUES (
    $1, $2, $3, $4
)
RETURNING name, description, pool_size, randomize, rules
`

type CreateDraftStrategyParams struct {
	Name        string
	Description string
	PoolSize    int32
	Randomize   bool
}

func (q *Queries) CreateDraftStrategy(ctx context.Context, arg CreateDraftStrategyParams) (Ci6ndexDraftStrategy, error) {
	row := q.db.QueryRow(ctx, createDraftStrategy,
		arg.Name,
		arg.Description,
		arg.PoolSize,
		arg.Randomize,
	)
	var i Ci6ndexDraftStrategy
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.PoolSize,
		&i.Randomize,
		&i.Rules,
	)
	return i, err
}

const createGameFromDraft = `-- name: CreateGameFromDraft :one
INSERT INTO ci6ndex.games
(
    draft_id, start_date
) VALUES (
    $1, $2
)
RETURNING id, draft_id, start_date, end_date, game_stats
`

type CreateGameFromDraftParams struct {
	DraftID   int64
	StartDate pgtype.Date
}

func (q *Queries) CreateGameFromDraft(ctx context.Context, arg CreateGameFromDraftParams) (Ci6ndexGame, error) {
	row := q.db.QueryRow(ctx, createGameFromDraft, arg.DraftID, arg.StartDate)
	var i Ci6ndexGame
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.StartDate,
		&i.EndDate,
		&i.GameStats,
	)
	return i, err
}

type CreateLeadersParams struct {
	LeaderName string
	CivName    string
}

const createRanking = `-- name: CreateRanking :one
INSERT INTO ci6ndex.rankings
(
    user_id, tier, leader_id
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, tier, leader_id
`

type CreateRankingParams struct {
	UserID   int64
	Tier     float64
	LeaderID int64
}

func (q *Queries) CreateRanking(ctx context.Context, arg CreateRankingParams) (Ci6ndexRanking, error) {
	row := q.db.QueryRow(ctx, createRanking, arg.UserID, arg.Tier, arg.LeaderID)
	var i Ci6ndexRanking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tier,
		&i.LeaderID,
	)
	return i, err
}

type CreateRankingsParams struct {
	UserID   int64
	Tier     float64
	LeaderID int64
}

const createUser = `-- name: CreateUser :one
INSERT INTO ci6ndex.users
(
    name, discord_name
) VALUES (
    $1, $2
)
RETURNING id, discord_name, name
`

type CreateUserParams struct {
	Name        string
	DiscordName string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Ci6ndexUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.DiscordName)
	var i Ci6ndexUser
	err := row.Scan(&i.ID, &i.DiscordName, &i.Name)
	return i, err
}

type CreateUsersParams struct {
	Name        string
	DiscordName string
}

const deleteOffered = `-- name: DeleteOffered :exec
DELETE FROM ci6ndex.offered
WHERE draft_id = $1
  AND user_id = $2
`

type DeleteOfferedParams struct {
	DraftID int64
	UserID  int64
}

func (q *Queries) DeleteOffered(ctx context.Context, arg DeleteOfferedParams) error {
	_, err := q.db.Exec(ctx, deleteOffered, arg.DraftID, arg.UserID)
	return err
}

const deleteRankings = `-- name: DeleteRankings :exec
DELETE FROM ci6ndex.rankings
RETURNING id, user_id, tier, leader_id
`

func (q *Queries) DeleteRankings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteRankings)
	return err
}

const getActiveDrafts = `-- name: GetActiveDrafts :many
SELECT id, draft_strategy, active, players FROM ci6ndex.drafts
WHERE active = true
`

func (q *Queries) GetActiveDrafts(ctx context.Context) ([]Ci6ndexDraft, error) {
	rows, err := q.db.Query(ctx, getActiveDrafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ci6ndexDraft
	for rows.Next() {
		var i Ci6ndexDraft
		if err := rows.Scan(
			&i.ID,
			&i.DraftStrategy,
			&i.Active,
			&i.Players,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDenormalizedDraftPicksForDraft = `-- name: GetDenormalizedDraftPicksForDraft :many
SELECT u.discord_name, l.leader_name, l.civ_name, l.discord_emoji_string, dp.draft_id, g.start_date
FROM ci6ndex.draft_picks dp
JOIN ci6ndex.games g on dp.draft_id = g.draft_id
JOIN ci6ndex.leaders l ON dp.leader_id = l.id
JOIN ci6ndex.users u ON dp.user_id = u.id
WHERE dp.draft_id = $1
`

type GetDenormalizedDraftPicksForDraftRow struct {
	DiscordName        string
	LeaderName         string
	CivName            string
	DiscordEmojiString pgtype.Text
	DraftID            int64
	StartDate          pgtype.Date
}

func (q *Queries) GetDenormalizedDraftPicksForDraft(ctx context.Context, draftID int64) ([]GetDenormalizedDraftPicksForDraftRow, error) {
	rows, err := q.db.Query(ctx, getDenormalizedDraftPicksForDraft, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDenormalizedDraftPicksForDraftRow
	for rows.Next() {
		var i GetDenormalizedDraftPicksForDraftRow
		if err := rows.Scan(
			&i.DiscordName,
			&i.LeaderName,
			&i.CivName,
			&i.DiscordEmojiString,
			&i.DraftID,
			&i.StartDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDraft = `-- name: GetDraft :one
SELECT id, draft_strategy, active, players FROM ci6ndex.drafts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDraft(ctx context.Context, id int64) (Ci6ndexDraft, error) {
	row := q.db.QueryRow(ctx, getDraft, id)
	var i Ci6ndexDraft
	err := row.Scan(
		&i.ID,
		&i.DraftStrategy,
		&i.Active,
		&i.Players,
	)
	return i, err
}

const getDraftPicksForDraft = `-- name: GetDraftPicksForDraft :many
SELECT id, draft_id, user_id, leader_id FROM ci6ndex.draft_picks
WHERE draft_id = $1
`

func (q *Queries) GetDraftPicksForDraft(ctx context.Context, draftID int64) ([]Ci6ndexDraftPick, error) {
	rows, err := q.db.Query(ctx, getDraftPicksForDraft, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ci6ndexDraftPick
	for rows.Next() {
		var i Ci6ndexDraftPick
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.UserID,
			&i.LeaderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDraftPicksForUserFromLastNGames = `-- name: GetDraftPicksForUserFromLastNGames :many
SELECT id, draft_id, user_id, leader_id FROM ci6ndex.draft_picks
WHERE user_id = (
    SELECT id FROM ci6ndex.users
    WHERE discord_name = $1
)
AND ci6ndex.draft_picks.draft_id IN (
   SELECT ci6ndex.games.draft_id FROM ci6ndex.games
    ORDER BY ci6ndex.games.start_date DESC LIMIT $2
)
`

type GetDraftPicksForUserFromLastNGamesParams struct {
	DiscordName string
	Limit       int32
}

func (q *Queries) GetDraftPicksForUserFromLastNGames(ctx context.Context, arg GetDraftPicksForUserFromLastNGamesParams) ([]Ci6ndexDraftPick, error) {
	rows, err := q.db.Query(ctx, getDraftPicksForUserFromLastNGames, arg.DiscordName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ci6ndexDraftPick
	for rows.Next() {
		var i Ci6ndexDraftPick
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.UserID,
			&i.LeaderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDraftStrategies = `-- name: GetDraftStrategies :many
SELECT name, description, pool_size, randomize, rules FROM ci6ndex.draft_strategies
`

func (q *Queries) GetDraftStrategies(ctx context.Context) ([]Ci6ndexDraftStrategy, error) {
	rows, err := q.db.Query(ctx, getDraftStrategies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ci6ndexDraftStrategy
	for rows.Next() {
		var i Ci6ndexDraftStrategy
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.PoolSize,
			&i.Randomize,
			&i.Rules,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDraftStrategy = `-- name: GetDraftStrategy :one
SELECT name, description, pool_size, randomize, rules FROM ci6ndex.draft_strategies
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetDraftStrategy(ctx context.Context, name string) (Ci6ndexDraftStrategy, error) {
	row := q.db.QueryRow(ctx, getDraftStrategy, name)
	var i Ci6ndexDraftStrategy
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.PoolSize,
		&i.Randomize,
		&i.Rules,
	)
	return i, err
}

const getDrafts = `-- name: GetDrafts :many
SELECT id, draft_strategy, active, players FROM ci6ndex.drafts
`

func (q *Queries) GetDrafts(ctx context.Context) ([]Ci6ndexDraft, error) {
	rows, err := q.db.Query(ctx, getDrafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ci6ndexDraft
	for rows.Next() {
		var i Ci6ndexDraft
		if err := rows.Scan(
			&i.ID,
			&i.DraftStrategy,
			&i.Active,
			&i.Players,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameByDraftID = `-- name: GetGameByDraftID :one
SELECT id, draft_id, start_date, end_date, game_stats FROM ci6ndex.games
WHERE draft_id = $1
`

func (q *Queries) GetGameByDraftID(ctx context.Context, draftID int64) (Ci6ndexGame, error) {
	row := q.db.QueryRow(ctx, getGameByDraftID, draftID)
	var i Ci6ndexGame
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.StartDate,
		&i.EndDate,
		&i.GameStats,
	)
	return i, err
}

const getLeader = `-- name: GetLeader :one
SELECT id, civ_name, leader_name, discord_emoji_string, banned FROM ci6ndex.leaders
         WHERE id = $1
         LIMIT 1
`

func (q *Queries) GetLeader(ctx context.Context, id int64) (Ci6ndexLeader, error) {
	row := q.db.QueryRow(ctx, getLeader, id)
	var i Ci6ndexLeader
	err := row.Scan(
		&i.ID,
		&i.CivName,
		&i.LeaderName,
		&i.DiscordEmojiString,
		&i.Banned,
	)
	return i, err
}

const getLeaderByNameAndCiv = `-- name: GetLeaderByNameAndCiv :one
SELECT id, civ_name, leader_name, discord_emoji_string, banned FROM ci6ndex.leaders
WHERE leader_name = $1
AND civ_name = $2
LIMIT 1
`

type GetLeaderByNameAndCivParams struct {
	LeaderName string
	CivName    string
}

func (q *Queries) GetLeaderByNameAndCiv(ctx context.Context, arg GetLeaderByNameAndCivParams) (Ci6ndexLeader, error) {
	row := q.db.QueryRow(ctx, getLeaderByNameAndCiv, arg.LeaderName, arg.CivName)
	var i Ci6ndexLeader
	err := row.Scan(
		&i.ID,
		&i.CivName,
		&i.LeaderName,
		&i.DiscordEmojiString,
		&i.Banned,
	)
	return i, err
}

const getLeaders = `-- name: GetLeaders :many
SELECT id, civ_name, leader_name, discord_emoji_string, banned FROM ci6ndex.leaders
`

func (q *Queries) GetLeaders(ctx context.Context) ([]Ci6ndexLeader, error) {
	rows, err := q.db.Query(ctx, getLeaders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ci6ndexLeader
	for rows.Next() {
		var i Ci6ndexLeader
		if err := rows.Scan(
			&i.ID,
			&i.CivName,
			&i.LeaderName,
			&i.DiscordEmojiString,
			&i.Banned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRankings = `-- name: GetRankings :many
SELECT id, user_id, tier, leader_id FROM ci6ndex.rankings
`

func (q *Queries) GetRankings(ctx context.Context) ([]Ci6ndexRanking, error) {
	rows, err := q.db.Query(ctx, getRankings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ci6ndexRanking
	for rows.Next() {
		var i Ci6ndexRanking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Tier,
			&i.LeaderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, discord_name, name FROM ci6ndex.users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (Ci6ndexUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i Ci6ndexUser
	err := row.Scan(&i.ID, &i.DiscordName, &i.Name)
	return i, err
}

const getUserByDiscordName = `-- name: GetUserByDiscordName :one
SELECT id, discord_name, name FROM ci6ndex.users WHERE discord_name = $1 LIMIT 1
`

func (q *Queries) GetUserByDiscordName(ctx context.Context, discordName string) (Ci6ndexUser, error) {
	row := q.db.QueryRow(ctx, getUserByDiscordName, discordName)
	var i Ci6ndexUser
	err := row.Scan(&i.ID, &i.DiscordName, &i.Name)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, discord_name, name FROM ci6ndex.users WHERE name = $1 LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (Ci6ndexUser, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i Ci6ndexUser
	err := row.Scan(&i.ID, &i.DiscordName, &i.Name)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, discord_name, name FROM ci6ndex.users
`

func (q *Queries) GetUsers(ctx context.Context) ([]Ci6ndexUser, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ci6ndexUser
	for rows.Next() {
		var i Ci6ndexUser
		if err := rows.Scan(&i.ID, &i.DiscordName, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readOffer = `-- name: ReadOffer :many
SELECT user_id, draft_id, offered FROM ci6ndex.offered
WHERE draft_id = $1
`

func (q *Queries) ReadOffer(ctx context.Context, draftID int64) ([]Ci6ndexOffered, error) {
	rows, err := q.db.Query(ctx, readOffer, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ci6ndexOffered
	for rows.Next() {
		var i Ci6ndexOffered
		if err := rows.Scan(&i.UserID, &i.DraftID, &i.Offered); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readOfferedForUser = `-- name: ReadOfferedForUser :one
SELECT user_id, draft_id, offered FROM ci6ndex.offered
WHERE draft_id = $1
  AND user_id = $2
`

type ReadOfferedForUserParams struct {
	DraftID int64
	UserID  int64
}

func (q *Queries) ReadOfferedForUser(ctx context.Context, arg ReadOfferedForUserParams) (Ci6ndexOffered, error) {
	row := q.db.QueryRow(ctx, readOfferedForUser, arg.DraftID, arg.UserID)
	var i Ci6ndexOffered
	err := row.Scan(&i.UserID, &i.DraftID, &i.Offered)
	return i, err
}

const removeDraftPick = `-- name: RemoveDraftPick :one
DELETE FROM ci6ndex.draft_picks
WHERE draft_id = $1
  AND user_id = $2
RETURNING id, draft_id, user_id, leader_id
`

type RemoveDraftPickParams struct {
	DraftID int64
	UserID  int64
}

func (q *Queries) RemoveDraftPick(ctx context.Context, arg RemoveDraftPickParams) (Ci6ndexDraftPick, error) {
	row := q.db.QueryRow(ctx, removeDraftPick, arg.DraftID, arg.UserID)
	var i Ci6ndexDraftPick
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.UserID,
		&i.LeaderID,
	)
	return i, err
}

const submitDraftPick = `-- name: SubmitDraftPick :one
INSERT INTO ci6ndex.draft_picks
(
    draft_id, leader_id, user_id
) VALUES (
    $1, $2, $3
) ON CONFLICT (draft_id, user_id)
DO UPDATE SET leader_id = $2
RETURNING id, draft_id, user_id, leader_id
`

type SubmitDraftPickParams struct {
	DraftID  int64
	LeaderID pgtype.Int8
	UserID   int64
}

func (q *Queries) SubmitDraftPick(ctx context.Context, arg SubmitDraftPickParams) (Ci6ndexDraftPick, error) {
	row := q.db.QueryRow(ctx, submitDraftPick, arg.DraftID, arg.LeaderID, arg.UserID)
	var i Ci6ndexDraftPick
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.UserID,
		&i.LeaderID,
	)
	return i, err
}

const updateGameFromDraftId = `-- name: UpdateGameFromDraftId :exec
UPDATE ci6ndex.games
SET start_date = $2
WHERE draft_id = $1
RETURNING id, draft_id, start_date, end_date, game_stats
`

type UpdateGameFromDraftIdParams struct {
	DraftID   int64
	StartDate pgtype.Date
}

func (q *Queries) UpdateGameFromDraftId(ctx context.Context, arg UpdateGameFromDraftIdParams) error {
	_, err := q.db.Exec(ctx, updateGameFromDraftId, arg.DraftID, arg.StartDate)
	return err
}

const wipeTables = `-- name: WipeTables :exec
DO $$
    DECLARE
        r RECORD;
    BEGIN
        FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'ci6ndex')
        LOOP
            IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'ci6ndex' AND tablename = r.tablename) THEN
                EXECUTE 'TRUNCATE TABLE ci6ndex.' || quote_ident(r.tablename) || ' CASCADE;';
            END IF;
        END LOOP;
    END $$
`

func (q *Queries) WipeTables(ctx context.Context) error {
	_, err := q.db.Exec(ctx, wipeTables)
	return err
}

const writeOffered = `-- name: WriteOffered :one
INSERT INTO ci6ndex.offered
(
    draft_id, user_id, offered
) VALUES (
    $1, $2, $3
) ON CONFLICT (draft_id, user_id)
DO UPDATE SET offered = $3
RETURNING user_id, draft_id, offered
`

type WriteOfferedParams struct {
	DraftID int64
	UserID  int64
	Offered []int64
}

func (q *Queries) WriteOffered(ctx context.Context, arg WriteOfferedParams) (Ci6ndexOffered, error) {
	row := q.db.QueryRow(ctx, writeOffered, arg.DraftID, arg.UserID, arg.Offered)
	var i Ci6ndexOffered
	err := row.Scan(&i.UserID, &i.DraftID, &i.Offered)
	return i, err
}
