DELETE FROM ci6ndex.draft_picks cascade;
DELETE FROM ci6ndex.rankings cascade;
DELETE FROM ci6ndex.leaders cascade;

INSERT INTO ci6ndex.leaders (civ_name, leader_name, discord_emoji_string, banned)
VALUES
    ('AMERICA', 'ABE','<:Abraham_Lincoln_Civ6:1229388680745975868>',true),
    ('AMERICA', 'BULLMOOSE TEDDY','<:Teddy_Roosevelt_Civ6:1229393265988472924>',false),
    ('AMERICA', 'ROUGH RIDER TEDDY'),
    ('AMERICA', 'TEDDY'),
    ('ARABIA', 'SALADIN SULTAN'),
    ('ARABIA', 'SALADIN VIZIR'),
    ('AUSTRALIA', 'JOHN CURTIN'),
    ('AZTEC', 'MONTEZUMA'),
    ('BABYLON', 'HAMMURABI'),
    ('BRAZIL', 'PEDRO II'),
    ('BYZANTIUM', 'BASIL II'),
    ('BYZANTIUM', 'THEODORA'),
    ('CANADA', 'WILFRID LAURIER'),
    ('CHINA', 'KUBLAI KHAN'),
    ('CHINA', 'QIN SHI HUANG UNIFIER'),
    ('CHINA', 'QIN SHI HUANG'),
    ('CHINA', 'WU ZEITAN'),
    ('CHINA', 'YONGLE'),
    ('CREE', 'POUNDMAKER'),
    ('DUTCH', 'WILHELMINA'),
    ('EGYPT', 'CLEOPATRA'),
    ('EGYPT', 'PTOLEMEIC CLEO'),
    ('EGYPT', 'RAMSEYS'),
    ('ENGLAND', 'ELEANOR OF AQUITAINE'),
    ('ENGLAND', 'ELIZABETH'),
    ('ENGLAND', 'STEAMY VICKY'),
    ('ENGLAND', 'VICTORIA'),
    ('ETHIOPIA', 'MENELIK II'),
    ('FRANCE', 'CATHERINE DE MEDICI'),
    ('FRANCE', 'ELEANOR AQUITAINE'),
    ('FRANCE', 'MAGNIFICENCE CATHERINE'),
    ('GAUL', 'AMBIORIX'),
    ('GEORGIA', 'TAMAR'),
    ('GERMANY', 'FREDERICK BARBAROSSA'),
    ('GERMANY', 'LUDWIG'),
    ('GRAN COLUMBIA', 'SIMON BOLIVAR'),
    ('GREECE', 'GORGO'),
    ('GREECE', 'PERICLES'),
    ('HUNGARY', 'MATTHIAS CORVINUS'),
    ('INCA', 'PACHACUTI'),
    ('INDIA', 'CHANDRAGUPTA'),
    ('INDIA', 'GHANDI'),
    ('INDONESIA', 'GITARJA'),
    ('JAPAN', 'HOJO TOKIMUNE'),
    ('JAPAN', 'TOKUGAWA'),
    ('KHMER', 'JAYAVARMAN VII'),
    ('KONGO', 'MVEMBA A NZINGA'),
    ('KONGO', 'NZINGA MBANDE'),
    ('KOREA', 'SEJONG'),
    ('KOREA', 'SEONDEOK'),
    ('MACEDON', 'ALEXANDER'),
    ('MALI', 'MANSA MUSA'),
    ('MALI', 'SUNDIATA KEITA'),
    ('MAORI', 'KUPE'),
    ('MAPUCHE', 'LAUTARO'),
    ('MAYA', 'LADY SIX SKY'),
    ('MONGOLIA', 'GENGHIS KHAN'),
    ('MONGOLIA', 'KUBLAI KHAN'),
    ('NORWAY', 'HARALD HARDRADA'),
    ('NORWAY', 'VARANGIA HARALD'),
    ('NUBIA', 'AMANITORE'),
    ('OTTOMAN', 'SULEIMAN MUHTEŞEM'),
    ('OTTOMAN', 'SULEIMAN'),
    ('PERSIA', 'CYRUS'),
    ('PERSIA', 'NADER SHAH'),
    ('PHOENICIAN', 'DIDO'),
    ('POLISH', 'JADWIGA'),
    ('PORTUGAL', 'JOÃO III'),
    ('ROME', 'JULIUS CAESER'),
    ('ROME', 'TRAJAN'),
    ('RUSSIA', 'PETER'),
    ('SCOTLAND', 'ROBERT THE BRUCE'),
    ('SCYTHIA', 'TOMYRIS'),
    ('SPAIN', 'PHILLIP II'),
    ('SUMERIA', 'GILGAMESH'),
    ('SWEDEN', 'KRISTINA'),
    ('VIETNAM', 'BÀ TRIỆU'),
    ('ZULU', 'SHAKA')
;

INSERT INTO ci6ndex.draft_strategies (name, description, randomize, pool_size, rules)
VALUES
(
 'AllPick',
 'Everyone can freely pick a leader, no restrictions.',
 false,
 null,
 null
),
(
 'RandomPick',
 'Everyone gets a single randomized leader.',
 true,
 1,
 null
),
(
 'RandomPickNoRepeats',
 'Everyone gets a pool of randomized leaders to pick from. They will not be offered any leaders they have picked in the past 3 games',
 true,
 3,
 '{"no_repeats": 3}'
)