INSERT INTO ci6ndex.leaders (civ_name, leader_name)
VALUES
    ('America', 'Abe'),
    ('America', 'Bullmoose Teddy'),
    ('America', 'Rough Rider Teddy'),
    ('America', 'Teddy'),
    ('Arabia', 'Saladin Sultan'),
    ('Arabia', 'Saladin Vizir'),
    ('Australia', 'John Curtin'),
    ('Aztec', 'Montezuma'),
    ('Babylon', 'Hammurabi'),
    ('Brazil', 'Pedro II'),
    ('Byzantium', 'Basil II'),
    ('Byzantium', 'Theodora'),
    ('Canada', 'Wilfrid Laurier'),
    ('China', 'Kublai Khan'),
    ('China', 'Qin Shi Huang Unifier'),
    ('China', 'Qin Shi Huang'),
    ('China', 'Wu Zeitan'),
    ('China', 'Yongle'),
    ('Cree', 'Poundmaker'),
    ('Dutch', 'Wilhelmina'),
    ('Egypt', 'Cleopatra'),
    ('Egypt', 'Ptolemeic Cleo'),
    ('Egypt', 'Ramseys'),
    ('England', 'Eleanor of Aquitaine'),
    ('England', 'Elizabeth'),
    ('England', 'Steamy Vicky'),
    ('England', 'Victoria'),
    ('Ethiopia', 'Menelik II'),
    ('France', 'Catherine de Medici'),
    ('France', 'Eleanor Aquitaine'),
    ('France', 'Magnificence Catherine'),
    ('Gaul', 'Ambiorix'),
    ('Georgia', 'Tamar'),
    ('Germany', 'Frederick Barbarossa'),
    ('Germany', 'Ludwig'),
    ('Gran Columbia', 'Simon Bolivar'),
    ('Greece', 'Gorgo'),
    ('Greece', 'Pericles'),
    ('Hungary', 'Matthias Corvinus'),
    ('Inca', 'Pachacuti'),
    ('India', 'Chandragupta'),
    ('India', 'Ghandi'),
    ('Indonesia', 'Gitarja'),
    ('Japan', 'Hojo Tokimune'),
    ('Japan', 'Tokugawa'),
    ('Khmer', 'Jayavarman VII'),
    ('Kongo', 'Mvemba a Nzinga'),
    ('Kongo', 'Nzinga Mbande'),
    ('Korea', 'Sejong'),
    ('Korea', 'Seondeok'),
    ('Macedon', 'Alexander'),
    ('Mali', 'Mansa Musa'),
    ('Mali', 'Sundiata Keita'),
    ('Maori', 'Kupe'),
    ('Mapuche', 'Lautaro'),
    ('Maya', 'Lady Six Sky'),
    ('Mongolia', 'Genghis Khan'),
    ('Mongolia', 'Kublai Khan'),
    ('Norway', 'Harald Hardrada'),
    ('Norway', 'Varangia Harald'),
    ('Nubia', 'Amanitore'),
    ('Ottoman', 'Suleiman Muhteşem'),
    ('Ottoman', 'Suleiman'),
    ('Persia', 'Cyrus'),
    ('Persia', 'Nader Shah'),
    ('Phoenician', 'Dido'),
    ('Polish', 'Jadwiga'),
    ('Portugal', 'João III'),
    ('Rome', 'Julius Caeser'),
    ('Rome', 'Trajan'),
    ('Russia', 'Peter'),
    ('Scotland', 'Robert the Bruce'),
    ('Scythia', 'Tomyris'),
    ('Spain', 'Phillip II'),
    ('Sumeria', 'Gilgamesh'),
    ('Sweden', 'Kristina'),
    ('Vietnam', 'Bà Triệu'),
    ('Zulu', 'Shaka')
;

INSERT INTO ci6ndex.draft_strategies (name, description, rules)
VALUES
(
 'AllPick',
 'Everyone can freely pick a leader, no restrictions.',
 null
),
(
 'RandomPick',
 'Everyone gets a randomized leader.',
 '{ "randomize": true }'
),
(
 'RandomPickPool3',
 'Everyone gets assigned a pool of 3 random leaders to pick from.',
 '{ "randomize": true, "pool_size": 3 }'
),
--     Potentially in the future add attr. like monger, culture etc?
(
 'RandomPickPool3Standard',
 'Everyone gets assigned a pool of 3 random leaders to pick from.',
 '{ "randomize": true, "pool_size": 3, "tiers_offered_min": {"1": 1}}'
)
;