version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./your-database.db:/app/your-database.db
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./your-database.db:/data/your-database.db